{% set name = "grip" %}
{% set version = "4.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3cf6dce0aa06edd663176914069af83f19dcb90f3a9c401271acfa71872f8ce3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - grip = grip:main

requirements:
  host:
    - python =2.7|>3.3
    - pip
  run:
    - python =2.7|>3.3
    - docopt >=0.4.0
    - Flask >=0.10.1
    - Markdown >=2.5.1
    - path-and-address >=2.0.1
    - Pygments >=1.6
    - requests >=2.4.1
    - werkzeug >=0.7

test:
  imports:
    - grip
  commands:
    - grip -h
    - pip check
  requires:
    - pip


about:
  home: https://github.com/joeyespo/grip
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Preview GitHub Markdown files like Readme locally before committing them.

  description: |
    Grip is a command-line server application written in Python that uses the GitHub markdown API 
    to render a local readme file. The styles come directly from GitHub, so you'll know exactly 
    how it will appear. Changes you make to the Readme will be instantly reflected in the browser 
    without requiring a page refresh.
  dev_url: https://github.com/joeyespo/grip

extra:
  recipe-maintainers:
    - synapticarbors
