{% set name = "grip" %}
{% set version = "4.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5e6ac48cd253892f0fbd0aaef3f74fe8169d8ed3d94a2e9be6bf1540e008e9f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - grip = grip:main

requirements:
  host:
    - python =2.7|>3.3
    - pip
  run:
    - python =2.7|>3.3
    - docopt >=0.4.0
    - Flask >=0.10.1
    - Markdown >=2.5.1
    - path-and-address >=2.0.1
    - Pygments >=1.6
    - requests >=2.4.1

test:
  imports:
    - grip
  commands:
    - grip -h


about:
  home: https://github.com/joeyespo/grip
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Preview GitHub Markdown files like Readme locally before committing them.

  description: |
    Grip is a command-line server application written in Python that uses the GitHub markdown API 
    to render a local readme file. The styles come directly from GitHub, so you'll know exactly 
    how it will appear. Changes you make to the Readme will be instantly reflected in the browser 
    without requiring a page refresh.
  dev_url: https://github.com/joeyespo/grip

extra:
  recipe-maintainers:
    - synapticarbors
