travis:
  secure:
    BINSTAR_TOKEN: RziUFlHvEH9vmj8FBVmcBiVLrjPS+EEAdMr2QNzUfYPKIHHouuxjISK6ikcJVGO+zQoO0UWT+zgO3QqH9wIDUKhxkWlw8sRDi7A34CefnVgWT2FW//liMMNIKt3qnmk8gMUmfv220Iw4lmrROMPdBYnGYWgD1ukMznrhorlFX1l1eAjcK/43oGlxROlTryTGyubYcTVNpmXSrGxZnRUPuAD50GTEcHFsS1GazV/wp1qL3RKtGFifFyRBcuCSno5Jm46R1lKJIMOjk3EuDf49o3BzyO8WBtwLeGa7hMRSM4ifteGEa7wm/HnKFQbbzyY8cYAioPIRdtC1BPFpP+8m9FLgBilG47OvJsf7VHeyw18xAEa1Jg1M9kCAzoiE/srI/kiOlvEYm0IqcM3DioAmqW3JNtaqjgEW8M6zLNMzp8HXlqLLYHnXlx6EaISPyUVLPbckozm7qYmupwfZnDmEj+GzqR530IulT5KOiMm3o6xDC14jYgquCgUxMqdc5UCzRZzNap+yQuzVX4Vy2ReQ9roNlThMZSRzDhtdh6ExT7U9H28NILLW+vYNXr3ZCBI8JSPtY1fcSvAlhyhF5SqZMOZ+Cs4bw2NAnP2AnZFHWODejopZA2akBBqAleVsFDWmnd8wMZPTinKURL8YqRXs6Ghm36g3/9Z+6SL4zhPBX8I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
