travis:
  secure:
    BINSTAR_TOKEN: a6CVP3nY3LYqP/ujNrS3tx69tK0wewY1It/mBE2rHayxwJ9FxrL23kssx6RA961In1VdG6IZRRv/RJKo10Sp9S/WyOEcp6WmReFB3UJCfUgTP0pxyxoxSJMbEJNo5gmSnuss3rY41+9NUjpgx+SWmtJGorlwdCa4SwmSQkT7ZsOm9Ye/dVGUqYzkk1MhvY9OauLo+q6KQ7owLMysr5nIPtfJ8UMLF0RJoadAzxOF+sMdloSPq8vLHbFLDeHi5Uf2ZHOQcnjXlZRjdn56q5kKbXnou43lhznCB0/x7s4Wcg/RsMacVFzp6nSQ4/Mkp+GgLA8z5nfpXLUpVsIirNgxu0zAxj77ZMszVLQ0FbdnRwSQzR2SxFcyy5uyDlSidzKSI+BoFY6i2gjWUo6RJySeHglTs9XBen4C7ahRhOgY3VBkaa9ObYzMvwBxtH7KeRfv6rmvcg3ZKJ++rOk1nHWHM7tGRJLyq7rUeq1VXlNsADWSWyUbAwg7eI44y4O+gc85kjP6aLT3MBQ4w/SbSmW5GVVtntJZdw+mkIWHVY+wWcHKyj6peYDdDzwnj4I7u1LbVAynP8j8DeEVedenUCcFheReTy5ASJhUqdcVbrt1zxKBaNiUATLmmJBVPOZQh1N9jaejYtX9eF8EyJKOcWFgXSxf5jM7+TZuMLNwu8YYeB0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
